basic_packages:
- curl
- wget
- net-tools
- openssh-server
- htop
- vim
- git
department_vlans:
- name: Development-Engineering
  state: active
  vlan_id: 10
- name: Guest-Network
  state: active
  vlan_id: 20
- name: IT
  state: active
  vlan_id: 30
- name: Sales-and-Marketing
  state: active
  vlan_id: 40
- name: Admin-Department
  state: active
  vlan_id: 50
- name: Human-Resource-Management
  state: active
  vlan_id: 60
- name: Accounts-and-Finance
  state: active
  vlan_id: 70
- name: Design
  state: active
  vlan_id: 80
- name: Marketing
  state: active
  vlan_id: 90
- name: Infrastructure-and-Security
  state: active
  vlan_id: 100
domain_name: company.local
server_packages:
- nginx
- mysql-server
- fail2ban
- ufw
- rsync
update_packages: false
