---
- name: Configure VLANs on Network Switches
  hosts: switches
  gather_facts: no
  connection: network_cli
  
  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable
    
  tasks:
    - name: Configure VLANs
      cisco.ios.ios_vlans:
        config:
        state: merged
        
    - name: Save configuration
      cisco.ios.ios_config:
        save_when: always
