---
# Network Devices Configuration Playbook
- name: Configure All Network Devices
  hosts: network_devices
  gather_facts: no
  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    
  tasks:
    - name: Configure VLANs on switches
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 10
            name: "Development-Engineering"
            state: active
          - vlan_id: 20
            name: "Guest-Network"
            state: active
          - vlan_id: 30
            name: "IT-Network"
            state: active
          - vlan_id: 40
            name: "Sales-and-Marketing"
            state: active
          - vlan_id: 50
            name: "Admin-Department"
            state: active
          - vlan_id: 60
            name: "Human-Resource-Management"
            state: active
          - vlan_id: 70
            name: "Accounts-and-Finance"
            state: active
          - vlan_id: 80
            name: "Design"
            state: active
          - vlan_id: 90
            name: "Marketing"
            state: active
          - vlan_id: 100
            name: "Infrastructure-and-Security"
            state: active
        state: merged
      when: '"switch" in inventory_hostname.lower()'
      tags: [vlans]

    - name: Configure switch management interface
      cisco.ios.ios_config:
        lines:
          - "ip address {{ ansible_host }} 255.255.255.0"
          - "no shutdown"
        parents: interface vlan1
      when: '"switch" in inventory_hostname.lower()'
      tags: [mgmt_interface]

    - name: Configure router interface
      cisco.ios.ios_config:
        lines:
          - "ip address {{ ansible_host }} 255.255.255.0"
          - "no shutdown"
        parents: interface FastEthernet0/0
      when: '"router" in inventory_hostname.lower() or inventory_hostname.startswith("R-")'
      tags: [router_interface]

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: always
      tags: [save]
