---
# Main API Deployment Playbook

# Configure Network Infrastructure Devices
- name: Configure Network Infrastructure Devices
  hosts: switches:routers:core_infrastructure
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: admin
  roles:
    - network-config
  tags: [network, infrastructure, switches, routers]

# Configure End User Devices  
- name: Configure End User Devices
  hosts: pcs:servers:printers
  gather_facts: yes
  become: yes
  connection: ssh
  vars:
    ansible_user: admin
  roles:
    - network-config
  tags: [endpoints, end_devices, pcs, servers, printers]
