---
# Network Infrastructure Only Playbook

- name: Configure Network Infrastructure Only
  hosts: switches:routers:core_infrastructure
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: admin
  
  tasks:
    # Configure department VLANs on switches
    - name: Configure department VLANs on switches using real data
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 10
            name: "Development-Engineering"
            state: active
          - vlan_id: 20
            name: "Guest-Network"
            state: active
          - vlan_id: 30
            name: "IT"
            state: active
          - vlan_id: 40
            name: "Sales-and-Marketing"
            state: active
          - vlan_id: 50
            name: "Admin-Department"
            state: active
          - vlan_id: 60
            name: "Human-Resource-Management"
            state: active
          - vlan_id: 70
            name: "Accounts-and-Finance"
            state: active
          - vlan_id: 80
            name: "Design"
            state: active
          - vlan_id: 90
            name: "Marketing"
            state: active
          - vlan_id: 100
            name: "Infrastructure-and-Security"
            state: active
        state: merged
      when: device_type == "switch"
      tags: [vlans, switches]

    # Save configuration
    - name: Save running configuration
      cisco.ios.ios_config:
        save_when: always
      when: device_type in ["switch", "router"]
      tags: [save, network_devices]
