all:
  children:
    pcs:
      hosts:
        TestV3_PC_10_1:
          ansible_connection: ssh
          ansible_host: 192.168.10.16
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_PC_10_2:
          ansible_connection: ssh
          ansible_host: 192.168.10.17
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_PC_10_3:
          ansible_connection: ssh
          ansible_host: 192.168.10.18
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_PC_10_4:
          ansible_connection: ssh
          ansible_host: 192.168.10.19
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_PC_10_5:
          ansible_connection: ssh
          ansible_host: 192.168.10.20
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_PC_10_6:
          ansible_connection: ssh
          ansible_host: 192.168.10.21
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_PC_20_1:
          ansible_connection: ssh
          ansible_host: 192.168.20.13
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_10:
          ansible_connection: ssh
          ansible_host: 192.168.20.22
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_11:
          ansible_connection: ssh
          ansible_host: 192.168.20.23
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_12:
          ansible_connection: ssh
          ansible_host: 192.168.20.24
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_13:
          ansible_connection: ssh
          ansible_host: 192.168.20.25
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_14:
          ansible_connection: ssh
          ansible_host: 192.168.20.26
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_15:
          ansible_connection: ssh
          ansible_host: 192.168.20.27
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_16:
          ansible_connection: ssh
          ansible_host: 192.168.20.28
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_17:
          ansible_connection: ssh
          ansible_host: 192.168.20.29
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_18:
          ansible_connection: ssh
          ansible_host: 192.168.20.30
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_19:
          ansible_connection: ssh
          ansible_host: 192.168.20.31
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_2:
          ansible_connection: ssh
          ansible_host: 192.168.20.14
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_20:
          ansible_connection: ssh
          ansible_host: 192.168.20.32
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_21:
          ansible_connection: ssh
          ansible_host: 192.168.20.33
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_22:
          ansible_connection: ssh
          ansible_host: 192.168.20.34
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_23:
          ansible_connection: ssh
          ansible_host: 192.168.20.35
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_24:
          ansible_connection: ssh
          ansible_host: 192.168.20.36
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_25:
          ansible_connection: ssh
          ansible_host: 192.168.20.37
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_26:
          ansible_connection: ssh
          ansible_host: 192.168.20.38
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_27:
          ansible_connection: ssh
          ansible_host: 192.168.20.39
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_28:
          ansible_connection: ssh
          ansible_host: 192.168.20.40
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_29:
          ansible_connection: ssh
          ansible_host: 192.168.20.41
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_3:
          ansible_connection: ssh
          ansible_host: 192.168.20.15
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_4:
          ansible_connection: ssh
          ansible_host: 192.168.20.16
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_5:
          ansible_connection: ssh
          ansible_host: 192.168.20.17
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_6:
          ansible_connection: ssh
          ansible_host: 192.168.20.18
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_7:
          ansible_connection: ssh
          ansible_host: 192.168.20.19
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_8:
          ansible_connection: ssh
          ansible_host: 192.168.20.20
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PC_20_9:
          ansible_connection: ssh
          ansible_host: 192.168.20.21
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
    printers:
      hosts:
        TestV3_PRT_10_1:
          ansible_connection: ssh
          ansible_host: 192.168.10.25
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_PRT_20_1:
          ansible_connection: ssh
          ansible_host: 192.168.20.46
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PRT_20_2:
          ansible_connection: ssh
          ansible_host: 192.168.20.47
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PRT_20_3:
          ansible_connection: ssh
          ansible_host: 192.168.20.48
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_PRT_20_4:
          ansible_connection: ssh
          ansible_host: 192.168.20.49
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
    routers:
      hosts:
        TestV3_R_10_1:
          ansible_connection: network_cli
          ansible_host: 192.168.10.14
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_R_10_2:
          ansible_connection: network_cli
          ansible_host: 192.168.10.15
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_R_20_1:
          ansible_connection: network_cli
          ansible_host: 192.168.20.12
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
    servers:
      hosts:
        TestV3_SRV_10_1:
          ansible_connection: ssh
          ansible_host: 192.168.10.22
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_SRV_10_2:
          ansible_connection: ssh
          ansible_host: 192.168.10.23
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_SRV_10_3:
          ansible_connection: ssh
          ansible_host: 192.168.10.24
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_SRV_20_1:
          ansible_connection: ssh
          ansible_host: 192.168.20.42
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_SRV_20_2:
          ansible_connection: ssh
          ansible_host: 192.168.20.43
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_SRV_20_3:
          ansible_connection: ssh
          ansible_host: 192.168.20.44
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_SRV_20_4:
          ansible_connection: ssh
          ansible_host: 192.168.20.45
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
    switches:
      hosts:
        TestV3_SW_10_1:
          ansible_connection: network_cli
          ansible_host: 192.168.10.10
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_SW_10_2:
          ansible_connection: network_cli
          ansible_host: 192.168.10.11
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_SW_10_3:
          ansible_connection: network_cli
          ansible_host: 192.168.10.12
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_SW_10_4:
          ansible_connection: network_cli
          ansible_host: 192.168.10.13
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_1
          testv3_device: true
          vlan_id: 10
        TestV3_SW_20_1:
          ansible_connection: network_cli
          ansible_host: 192.168.20.10
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
        TestV3_SW_20_2:
          ansible_connection: network_cli
          ansible_host: 192.168.20.11
          ansible_network_os: ios
          ansible_password: admin
          ansible_user: admin
          department: TestV3_Department_2
          testv3_device: true
          vlan_id: 20
