---
# Switch Configuration Tasks
- name: Configure VLANs
  cisco.ios.ios_vlans:
    config: "{{ vlans_config }}"
    state: merged
  tags: [vlans]

- name: Configure L2 interfaces
  cisco.ios.ios_l2_interfaces:
    config: "{{ switch_interfaces }}"
    state: merged
  tags: [interfaces]

- name: Configure switch base settings
  cisco.ios.ios_config:
    lines:
      - "hostname {{ inventory_hostname }}"
      - "service password-encryption"
      - "ip domain-name {{ domain_name | default('company.local') }}"
      - "enable secret admin"
      - "username admin privilege 15 secret admin"
      - "ip default-gateway {{ gateway | default('192.168.1.254') }}"
      - "crypto key generate rsa modulus 1024"
      - "ip ssh version 2"
    parents: []
  tags: [base_config]

- name: Configure management interface
  cisco.ios.ios_config:
    lines:
      - "ip address {{ ansible_host }} 255.255.255.0"
      - "no shutdown"
    parents: interface vlan1
  tags: [mgmt_interface]

- name: Configure VTY lines for SSH access
  cisco.ios.ios_config:
    lines:
      - "login local"
      - "transport input ssh"
    parents: line vty 0 15
  tags: [ssh_access]

- name: Save configuration
  cisco.ios.ios_config:
    save_when: always
  tags: [save]
