ansible_become: 'yes'
ansible_become_method: enable
ansible_connection: network_cli
ansible_network_os: ios
ansible_password: admin
ansible_user: admin
dns_servers:
- 8.8.8.8
- 8.8.4.4
domain_name: company.local
ntp_servers:
- 192.168.1.1
- 192.168.1.2
