---
# Router Configuration Tasks
- name: Configure router base settings
  cisco.ios.ios_config:
    lines:
      - "hostname {{ inventory_hostname }}"
      - "ip routing"
      - "ip cef"
      - "service password-encryption"
      - "ip domain-name {{ domain_name | default('company.local') }}"
      - "enable secret admin"
      - "username admin privilege 15 secret admin"
      - "crypto key generate rsa modulus 1024"
      - "ip ssh version 2"
    parents: []
  tags: [base_config]

- name: Configure router interface
  cisco.ios.ios_config:
    lines:
      - "ip address {{ ansible_host }} 255.255.255.0"
      - "no shutdown"
    parents: interface FastEthernet0/0
  tags: [interface]

- name: Configure VTY lines for SSH access
  cisco.ios.ios_config:
    lines:
      - "login local"
      - "transport input ssh"
    parents: line vty 0 15
  tags: [ssh_access]

- name: Save configuration
  cisco.ios.ios_config:
    save_when: always
  tags: [save]
